require('dotenv').config({ path: '../.env' });
const { pool } = require('../config/db');

const statusColor = (score) => {
  if (!score) return 'yellow';
  if (score >= 4.5) return 'green';
  if (score >= 4.0) return 'blue';
  if (score >= 3.0) return 'yellow';
  return 'red';
};

const firms = [
  {
    name: 'Lucid Flex',
    discount_code: 'RTF',
    overall_score: 4.8,
    platforms: 'NinjaTrader, Tradovate, TradingView, MotiveWave, Quantower, Sierra Chart, Jigsaw, Bookmap, ATAS, R|Trader Pro, Multicharts',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 84, fifty_k_initial_cost: 84, without_discount_usd: 140, discount_usd: 56, discount_percent: 40,
    activation_fee: 0, max_accounts: '5 Funded, Unlimited Evals', profit_split: '90/10',
    max_withdrawal: '(1-6) $2,000', profit_target: '$4,000 for max withdrawl, $1,000 for min',
    drawdown_limit: 'EOD, $2,000', dll: 'None', buffer: false, buffer_amount: null,
    days_to_pass: '2', days_to_payout: '5 min of $150', eval: '50%', pa: '0%', reset_fee: '$76',
    dca: true, news: true, bots: true, copy_trade: true, vpn: false, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'Lucid',
  },
  {
    name: 'Lucid Pro',
    discount_code: 'RTF',
    overall_score: 4.8,
    platforms: 'NinjaTrader, Tradovate, TradingView, MotiveWave, Quantower, Sierra Chart, Jigsaw, Bookmap, ATAS, R|Trader Pro, Multicharts',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 111, fifty_k_initial_cost: 111, without_discount_usd: 185, discount_usd: 74, discount_percent: 40,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: '(1) $1,500 (2-4) up to $3,000 (w/bonus)', profit_target: '$3,000',
    drawdown_limit: null, dll: '$1,200', buffer: false, buffer_amount: null,
    days_to_pass: '2', days_to_payout: '3', eval: '60%', pa: '40%', reset_fee: '$120',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Lucid',
  },
  {
    name: 'Lucid Direct',
    discount_code: 'RTF',
    overall_score: 4.8,
    platforms: 'NinjaTrader, Tradovate, TradingView, MotiveWave, Quantower, Sierra Chart, Jigsaw, Bookmap, ATAS, R|Trader Pro, Multicharts',
    account_category: 'Straight to Funded (S2F)',
    fifty_k_all_in: 364, fifty_k_initial_cost: 364, without_discount_usd: 520, discount_usd: 156, discount_percent: 30,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: '(1-3) $2,000 (4-6) $2,500', profit_target: '$3,000 (first), $2,500 after',
    drawdown_limit: null, dll: '$1,200 until $52,100 then 60% of highest day profit after', buffer: false, buffer_amount: null,
    days_to_pass: 'N/A', days_to_payout: '8', eval: 'N/A', pa: null, reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Lucid',
  },
  {
    name: 'YRM Prop - Starter Challenge (50K)',
    discount_code: 'RTF',
    overall_score: 4.8,
    platforms: 'DX Feed, Volumetrica, Quantower, ATAS',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 74, fifty_k_initial_cost: 74, without_discount_usd: 149, discount_usd: 75, discount_percent: 51,
    activation_fee: 0, max_accounts: 'Unlimited Challenge, 3 Prime / Instant Prime', profit_split: '90/10',
    max_withdrawal: '1st-$1,500, 2nd-$2,000, 3rd-$2,500, 4th-$2,750', profit_target: '$3,000',
    drawdown_limit: 'EOD, $2000', dll: 'None', buffer: true, buffer_amount: '$100',
    days_to_pass: '2', days_to_payout: '6', eval: '50%', pa: '35%', reset_fee: 'N/A',
    dca: true, news: true, bots: false, copy_trade: true, vpn: true, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'YRM Prop',
  },
  {
    name: 'YRM Prop - Starter Challenge (25K)',
    discount_code: 'RTF',
    overall_score: 4.8,
    platforms: 'DX Feed, Volumetrica, Quantower, ATAS',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 49, fifty_k_initial_cost: 49, without_discount_usd: 99, discount_usd: 50, discount_percent: 51,
    activation_fee: 0, max_accounts: null, profit_split: '90/10',
    max_withdrawal: '1st-$1000, 2nd-$1000, 3rd-$1000, 4th-$1250', profit_target: '$1,500',
    drawdown_limit: 'EOD, $1000', dll: null, buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: null, eval: null, pa: null, reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'YRM Prop',
  },
  {
    name: 'YRM Prop Instant Prime (50K)',
    discount_code: 'RTF',
    overall_score: 4.8,
    platforms: 'DX Feed, Volumetrica, Quantower, ATAS',
    account_category: 'Straight to Funded (S2F)',
    fifty_k_all_in: 300, fifty_k_initial_cost: 300, without_discount_usd: 599, discount_usd: 300, discount_percent: 50,
    activation_fee: 0, max_accounts: null, profit_split: '90/10',
    max_withdrawal: '$2,000 first $2,500 after', profit_target: '$3,000 first, $2,000 after',
    drawdown_limit: 'EOD, $2000', dll: '$1,500 Soft', buffer: false, buffer_amount: null,
    days_to_pass: 'N/A', days_to_payout: '8', eval: 'N/A', pa: '20%', reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'YRM Prop',
  },
  {
    name: 'Purdia Eval (EOD)',
    discount_code: 'RTF',
    overall_score: 4.3,
    platforms: 'NinjaTrader, Tradovate, TradingView',
    account_category: 'Eval',
    fifty_k_all_in: 264, fifty_k_initial_cost: 134, without_discount_usd: 179, discount_usd: 45, discount_percent: 25,
    activation_fee: 130, max_accounts: '3', profit_split: '70/30',
    max_withdrawal: 'N/A', profit_target: '$3,000',
    drawdown_limit: '$2000 EOD', dll: '$1,000', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '5', days_to_payout: '5 min of $200 after buffer', eval: '0%', pa: null, reset_fee: '$99',
    dca: true, news: true, bots: false, copy_trade: null, vpn: null, micro_scalping: true,
    featured: false, importance: 'medium', group_name: 'Purdia',
  },
  {
    name: 'Funded Futures Network Standard',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'Onyx, Quantower, EdgeProX, Motivewave Mobile, NinjaTrader',
    account_category: 'Eval (Exhibition)',
    fifty_k_all_in: 75, fifty_k_initial_cost: 75, without_discount_usd: 150, discount_usd: 75, discount_percent: 50,
    activation_fee: 0, max_accounts: '10 Accts (only 5 copy trade at once)', profit_split: '80/20 for first 5k, then 90/10',
    max_withdrawal: 'No limit above buffer', profit_target: '$3,000',
    drawdown_limit: '$2000 EOT', dll: '$0', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '7', days_to_payout: '3', eval: '40%', pa: '40%', reset_fee: '$100',
    dca: true, news: false, bots: false, copy_trade: true, vpn: true, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'Funded Futures Network',
  },
  {
    name: 'Funded Futures Network Express MAX',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'Onyx, Quantower, EdgeProX, Motivewave Mobile, NinjaTrader',
    account_category: 'Eval (No Exhibition)',
    fifty_k_all_in: 93, fifty_k_initial_cost: 93, without_discount_usd: 185, discount_usd: 93, discount_percent: 50,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: 'Static +$100 After Buffer', profit_target: null,
    drawdown_limit: '$2000 Intraday Trailing', dll: null, buffer: true, buffer_amount: '$2,000',
    days_to_pass: '2', days_to_payout: 'Same Day', eval: '50%', pa: '50%', reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Funded Futures Network',
  },
  {
    name: 'Bulenox Option 1',
    discount_code: 'RTF89',
    overall_score: 4.8,
    platforms: 'NinjaTrader, R|Trader Pro, Tiger Trade, Optimus Flow, Inside Edge, Volfix.Net, ATAS, Scalp, Overcharts, MedVed, Quantower, Quick Screen Trading, Scalp Tool, TSLAB, Trade Navigator, Sierra Chart, MultiCharts, Photon, MotiveWave, RInvestor, Bookmap X-Ray',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 167, fifty_k_initial_cost: 19, without_discount_usd: 175, discount_usd: 156, discount_percent: 89,
    activation_fee: 148, max_accounts: '3 accts (up to 11)', profit_split: '100% first 10k, 90/10 after',
    max_withdrawal: '$1,500 (first 3 payouts) no limits after', profit_target: '$3,000',
    drawdown_limit: 'Trailing $2500', dll: '$0', buffer: true, buffer_amount: '$2,600',
    days_to_pass: '1', days_to_payout: '10', eval: '0%', pa: '40%', reset_fee: '$78',
    dca: true, news: true, bots: false, copy_trade: true, vpn: false, micro_scalping: true,
    featured: true, importance: 'high', group_name: 'Bulenox',
  },
  {
    name: 'Bulenox Option 2',
    discount_code: 'RTF75',
    overall_score: 4.8,
    platforms: 'NinjaTrader, R|Trader Pro, Tiger Trade, Optimus Flow, Inside Edge, Volfix.Net, ATAS, Scalp, Overcharts, MedVed, Quantower, Quick Screen Trading, Scalp Tool, TSLAB, Trade Navigator, Sierra Chart, MultiCharts, Photon, MotiveWave, RInvestor, Bookmap X-Ray',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 192, fifty_k_initial_cost: 44, without_discount_usd: 175, discount_usd: 131, discount_percent: 75,
    activation_fee: 148, max_accounts: '3 accts (up to 11)', profit_split: '100% first 10k, 90/10 after',
    max_withdrawal: null, profit_target: null,
    drawdown_limit: 'EOD $2500', dll: '$1100 soft', buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: null, eval: null, pa: null, reset_fee: '$78',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Bulenox',
  },
  {
    name: 'Tradeify - Growth',
    discount_code: '3879',
    overall_score: 4.6,
    platforms: 'Tradovate, ProjectX, NinjaTrader',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 83, fifty_k_initial_cost: 83, without_discount_usd: 139, discount_usd: 56, discount_percent: 40,
    activation_fee: 0, max_accounts: '5', profit_split: '90/10',
    max_withdrawal: '$3,000', profit_target: '$2,500',
    drawdown_limit: 'EOD, $2000', dll: '$1,250', buffer: true, buffer_amount: '$2,100',
    days_to_pass: '1', days_to_payout: '2', eval: '35%', pa: '35%', reset_fee: '$95',
    dca: true, news: true, bots: true, copy_trade: true, vpn: false, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'Tradeify',
  },
  {
    name: 'Tradeify - Select',
    discount_code: '3879',
    overall_score: 4.6,
    platforms: 'Tradovate, ProjectX, NinjaTrader',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 95, fifty_k_initial_cost: 95, without_discount_usd: 159, discount_usd: 64, discount_percent: 40,
    activation_fee: 0, max_accounts: null, profit_split: '90/10',
    max_withdrawal: '$1,000', profit_target: '$2,500',
    drawdown_limit: 'EOD, $2000', dll: '$1,000', buffer: true, buffer_amount: '$3,000',
    days_to_pass: '3', days_to_payout: '2', eval: '35%', pa: '35%', reset_fee: '$95',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Tradeify',
  },
  {
    name: 'Tradeify - Lightning',
    discount_code: '3879',
    overall_score: 4.6,
    platforms: 'Tradovate, ProjectX, NinjaTrader',
    account_category: 'Direct to Funded (S2F)',
    fifty_k_all_in: 281, fifty_k_initial_cost: 281, without_discount_usd: 469, discount_usd: 188, discount_percent: 40,
    activation_fee: 0, max_accounts: null, profit_split: '90/10',
    max_withdrawal: 'N/A', profit_target: 'None',
    drawdown_limit: 'EOD, $2000', dll: 'N/A', buffer: true, buffer_amount: '$2,100',
    days_to_pass: 'N/A', days_to_payout: '2', eval: 'N/A', pa: '20%', reset_fee: '$0',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Tradeify',
  },
  {
    name: 'TradeDay Intraday',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'NinjaTrader, Tradovate, TradingView, ProjectX, JigSaw Trading',
    account_category: 'Eval',
    fifty_k_all_in: 88, fifty_k_initial_cost: 88, without_discount_usd: 125, discount_usd: 38, discount_percent: 30,
    activation_fee: 0, max_accounts: '6', profit_split: '80/20',
    max_withdrawal: '$5,000', profit_target: '$3,000',
    drawdown_limit: 'Intraday $2000', dll: 'None', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '5', days_to_payout: '1', eval: '30%', pa: 'None', reset_fee: 'N/A',
    dca: true, news: false, bots: false, copy_trade: true, vpn: false, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'TradeDay',
  },
  {
    name: 'TradeDay Static',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'NinjaTrader, Tradovate, TradingView, ProjectX, JigSaw Trading',
    account_category: 'Static',
    fifty_k_all_in: 116, fifty_k_initial_cost: 116, without_discount_usd: 165, discount_usd: 50, discount_percent: 30,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: null, profit_target: '$1,500',
    drawdown_limit: 'Static $500', dll: null, buffer: true, buffer_amount: '$500',
    days_to_pass: null, days_to_payout: null, eval: null, pa: null, reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'TradeDay',
  },
  {
    name: 'FundedFuturesFamily (Prime)',
    discount_code: 'RTF',
    overall_score: 4.7,
    platforms: 'Tradovate, WealthCharts',
    account_category: 'Eval',
    fifty_k_all_in: 98, fifty_k_initial_cost: 98, without_discount_usd: 179, discount_usd: 81, discount_percent: 45,
    activation_fee: 0, max_accounts: '5', profit_split: '90/10',
    max_withdrawal: '$2,000', profit_target: '$3,000',
    drawdown_limit: 'EoD $2000', dll: 'None', buffer: true, buffer_amount: '$2,100',
    days_to_pass: '1', days_to_payout: '3', eval: 'N/A', pa: '40%', reset_fee: '$159',
    dca: true, news: true, bots: false, copy_trade: false, vpn: false, micro_scalping: true,
    featured: true, importance: 'high', group_name: 'FundedFuturesFamily',
  },
  {
    name: 'FundedFuturesFamily (Premier)',
    discount_code: 'RTF',
    overall_score: 4.7,
    platforms: 'Tradovate, WealthCharts',
    account_category: 'Eval',
    fifty_k_all_in: 87, fifty_k_initial_cost: 87, without_discount_usd: 159, discount_usd: 72, discount_percent: 45,
    activation_fee: 0, max_accounts: null, profit_split: '50% of profit',
    max_withdrawal: null, profit_target: null,
    drawdown_limit: 'EoD $1500', dll: null, buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: '5', eval: null, pa: '-', reset_fee: '$99',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'FundedFuturesFamily',
  },
  {
    name: 'E8 Signature',
    discount_code: 'E8RTF',
    overall_score: 4.5,
    platforms: 'Tradovate, TradingView, E8 Futures',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 135, fifty_k_initial_cost: 135, without_discount_usd: 150, discount_usd: 15, discount_percent: 10,
    activation_fee: 0, max_accounts: '5', profit_split: '80/20',
    max_withdrawal: '(1-2) $1,250 (3-4) $2,250, 5 $3,250', profit_target: '$3,000',
    drawdown_limit: 'EOD, $2,000', dll: '$1,000 in Funded (soft)', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '1', days_to_payout: '3', eval: '0%', pa: '35%', reset_fee: '10% off',
    dca: true, news: false, bots: false, copy_trade: true, vpn: true, micro_scalping: true,
    featured: false, importance: 'medium', group_name: 'E8',
  },
  {
    name: 'Humble Futures (Standard Path)',
    discount_code: 'RTF',
    overall_score: 3.7,
    platforms: 'Quantower (Partner Platform), Rithmic Pro, Finamark, Investor/RT, ATAS, MotiveWave, CTS T4, Jigsaw, Optimus Flow, CQG, Trade Navigator, VolFix, Sierra Charts, Multicharts, EdgeProX, Onyx',
    account_category: 'Eval',
    fifty_k_all_in: 179, fifty_k_initial_cost: 29, without_discount_usd: 190, discount_usd: 162, discount_percent: 85,
    activation_fee: 150, max_accounts: 'Unlimited Evaluation', profit_split: '25K then 90/10 after',
    max_withdrawal: '$2,000', profit_target: '$2,500',
    drawdown_limit: 'Intraday $2000 or Static $500 (100k)', dll: 'None', buffer: false, buffer_amount: null,
    days_to_pass: '4', days_to_payout: '5', eval: '40%', pa: '30%', reset_fee: '$14.48 (after 92% off)',
    dca: true, news: true, bots: false, copy_trade: true, vpn: false, micro_scalping: false,
    featured: false, importance: 'low', group_name: 'Humble Futures',
  },
  {
    name: 'Humble Futures (Express Path)',
    discount_code: 'RTF',
    overall_score: 3.7,
    platforms: 'Quantower (Partner Platform), Rithmic Pro, Finamark, Investor/RT, ATAS, MotiveWave, CTS T4, Jigsaw, Optimus Flow, CQG, Trade Navigator, VolFix, Sierra Charts, Multicharts, EdgeProX, Onyx',
    account_category: 'Eval',
    fifty_k_all_in: 91, fifty_k_initial_cost: 91, without_discount_usd: 130, discount_usd: 39, discount_percent: 30,
    activation_fee: 0, max_accounts: '10 Accounts Max', profit_split: null,
    max_withdrawal: null, profit_target: null,
    drawdown_limit: 'EOD or Intraday $2000', dll: null, buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: null, eval: '0% for Trailing 30% for EOD', pa: null, reset_fee: '$99 (after 45% off)',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'low', group_name: 'Humble Futures',
  },
  {
    name: 'BluSky Premium',
    discount_code: '30OFF',
    overall_score: 4.8,
    platforms: 'Volumetrica, VolSys/Deepchart, VolBook/Deepdom, NinjaTrader Prop, Tradovate Prop, R|Trader Pro, MotiveWave, Quantower, Jigsaw, ATAS, Sierra Chart, Bookmap, TradingView',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 112, fifty_k_initial_cost: 112, without_discount_usd: 160, discount_usd: 48, discount_percent: 30,
    activation_fee: 0, max_accounts: '5 across (eval, BluLive, D2F) or 3 Instant', profit_split: '90/10',
    max_withdrawal: '$3,000 in SimFunded per week, no limits after', profit_target: '$3000 in eval, $3000 to withdraw',
    drawdown_limit: 'EOD, $2000', dll: '$1,200', buffer: true, buffer_amount: '$1,000',
    days_to_pass: '5', days_to_payout: '1', eval: '30%', pa: '0%', reset_fee: '$65',
    dca: true, news: true, bots: true, copy_trade: true, vpn: true, micro_scalping: true,
    featured: true, importance: 'high', group_name: 'BluSky',
  },
  {
    name: 'BluSky Static (150k)',
    discount_code: '30OFF',
    overall_score: 4.8,
    platforms: 'Volumetrica, VolSys/Deepchart, VolBook/Deepdom, NinjaTrader Prop, Tradovate Prop, R|Trader Pro, MotiveWave, Quantower, Jigsaw, ATAS, Sierra Chart, Bookmap, TradingView',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 119, fifty_k_initial_cost: 119, without_discount_usd: 170, discount_usd: 51, discount_percent: 30,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: '$3,000 in SimFunded per week, no limits after', profit_target: '$3000 in eval, $2000 to withdraw',
    drawdown_limit: 'Static $1000', dll: '$0', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '5', days_to_payout: '1', eval: '30%', pa: '0%', reset_fee: '$65',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'BluSky',
  },
  {
    name: 'BluSky Instant',
    discount_code: null,
    overall_score: 4.8,
    platforms: 'Volumetrica, VolSys/Deepchart, VolBook/Deepdom, NinjaTrader Prop, Tradovate Prop, R|Trader Pro, MotiveWave, Quantower, Jigsaw, ATAS, Sierra Chart, Bookmap, TradingView',
    account_category: 'Direct to Funded (S2F)',
    fifty_k_all_in: 599, fifty_k_initial_cost: 599, without_discount_usd: 599, discount_usd: 0, discount_percent: 0,
    activation_fee: 0, max_accounts: null, profit_split: '80/20',
    max_withdrawal: 'N/A', profit_target: 'Above $3000 and 21% consistency rule',
    drawdown_limit: 'Trailing $2000', dll: 'N/A', buffer: true, buffer_amount: '$3,000',
    days_to_pass: 'N/A', days_to_payout: '5', eval: 'N/A', pa: '0.21', reset_fee: '0',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'BluSky',
  },
  {
    name: 'E2T The Career Path',
    discount_code: 'RTF',
    overall_score: 4.7,
    platforms: 'NinjaTrader, Finamark, R|Trader Pro, Overcharts, Inside Edge Trader, Investor RT, MotiveWave, MultiCharts, Bookmap, QScalp, QSI-QuickScreen, ScalpTool, Trade Navigator, Volfix.net, Jigsaw, ATAS, Sierra Chart, QuantowerATAS',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 95, fifty_k_initial_cost: 95, without_discount_usd: 190, discount_usd: 95, discount_percent: 50,
    activation_fee: 0, max_accounts: '3', profit_split: '80/20',
    max_withdrawal: '$2400 then move to live', profit_target: '$3,000',
    drawdown_limit: 'EOD in Eval and LiveSim, Trailing in Live, $2,000', dll: '$1,100 (hard)', buffer: false, buffer_amount: null,
    days_to_pass: '10', days_to_payout: '1', eval: '30%', pa: '0%', reset_fee: '$65',
    dca: true, news: true, bots: false, copy_trade: false, vpn: true, micro_scalping: true,
    featured: true, importance: 'high', group_name: 'E2T',
  },
  {
    name: 'Savius Viper (50k)',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'DX Feed, VolSys, VolBook, Quantower, ATAS',
    account_category: 'S2F (Straight To Funded)',
    fifty_k_all_in: 160, fifty_k_initial_cost: 160, without_discount_usd: 399, discount_usd: 239, discount_percent: 60,
    activation_fee: 0, max_accounts: '5', profit_split: '80/20',
    max_withdrawal: '$1,500 (up to 3 times)', profit_target: '$2,500',
    drawdown_limit: 'Trailing, $2,000', dll: '$800 Hard', buffer: false, buffer_amount: null,
    days_to_pass: 'N/A', days_to_payout: '10', eval: 'N/A', pa: '20%', reset_fee: '$119',
    dca: true, news: true, bots: false, copy_trade: true, vpn: true, micro_scalping: true,
    featured: true, importance: 'high', group_name: 'Savius',
  },
  {
    name: 'Savius Typhoon (100k)',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'DX Feed, VolSys, VolBook, Quantower, ATAS',
    account_category: 'S2F (Straight To Funded)',
    fifty_k_all_in: 240, fifty_k_initial_cost: 240, without_discount_usd: 599, discount_usd: 359, discount_percent: 60,
    activation_fee: 0, max_accounts: '5', profit_split: '80/20',
    max_withdrawal: null, profit_target: '$5,000',
    drawdown_limit: 'Trailing, $4,000', dll: '$1,300', buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: null, eval: null, pa: null, reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Savius',
  },
  {
    name: 'Savius Raptor (25k)',
    discount_code: 'RTF',
    overall_score: 4.6,
    platforms: 'DX Feed, VolSys, VolBook, Quantower, ATAS',
    account_category: 'S2F (Straight To Funded)',
    fifty_k_all_in: 114, fifty_k_initial_cost: 114, without_discount_usd: 285, discount_usd: 171, discount_percent: 60,
    activation_fee: 0, max_accounts: '5', profit_split: '80/20',
    max_withdrawal: null, profit_target: '$1,250',
    drawdown_limit: 'Trailing, $1,000', dll: '$400', buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: null, eval: null, pa: null, reset_fee: '$100',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Savius',
  },
  {
    name: 'FundedNext - Rapid ($50k)',
    discount_code: null,
    overall_score: 4.5,
    platforms: 'Tradovate, TradingView, NinjaTrader',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 160, fifty_k_initial_cost: 160, without_discount_usd: 200, discount_usd: 40, discount_percent: 20,
    activation_fee: 0, max_accounts: '$700k across challenge, $300k across FundedNext', profit_split: 'up to 100%',
    max_withdrawal: '$1,500', profit_target: '$3,000',
    drawdown_limit: 'EOD, $2,000', dll: 'None', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '1', days_to_payout: '3', eval: '0%', pa: '40%', reset_fee: '$132',
    dca: true, news: true, bots: true, copy_trade: true, vpn: true, micro_scalping: false,
    featured: false, importance: 'medium', group_name: 'FundedNext',
  },
  {
    name: 'Alpha Futures - Zero',
    discount_code: null,
    overall_score: 4.9,
    platforms: 'Tradovate, NinjaTrader, TradingView, ProjectX, Quantower',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 119, fifty_k_initial_cost: 119, without_discount_usd: 119, discount_usd: 0, discount_percent: 0,
    activation_fee: 0, max_accounts: '5', profit_split: '90/10',
    max_withdrawal: '$1,500 max', profit_target: '$3,000',
    drawdown_limit: 'EOD, $2000', dll: '$1,000 Soft', buffer: false, buffer_amount: null,
    days_to_pass: '1', days_to_payout: '5', eval: '0%', pa: '40%', reset_fee: '$79',
    dca: true, news: true, bots: false, copy_trade: true, vpn: false, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'Alpha Futures',
  },
  {
    name: 'Alpha Futures - Premium',
    discount_code: 'PREMIUM',
    overall_score: 4.9,
    platforms: 'Tradovate, NinjaTrader, TradingView, ProjectX, Quantower',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 208, fifty_k_initial_cost: 59, without_discount_usd: 79, discount_usd: 20, discount_percent: 25,
    activation_fee: 149, max_accounts: null, profit_split: null,
    max_withdrawal: 'None', profit_target: null,
    drawdown_limit: 'None on Eval, $1,000 Soft Breach on PA', dll: null, buffer: false, buffer_amount: null,
    days_to_pass: '2', days_to_payout: '14', eval: '50%', pa: 'N/A', reset_fee: '$59',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Alpha Futures',
  },
  {
    name: 'Alpha Futures - Advanced',
    discount_code: null,
    overall_score: 4.9,
    platforms: 'Tradovate, NinjaTrader, TradingView, ProjectX, Quantower',
    account_category: 'Eval (Test)',
    fifty_k_all_in: 288, fifty_k_initial_cost: 139, without_discount_usd: 139, discount_usd: 0, discount_percent: 0,
    activation_fee: 149, max_accounts: '3', profit_split: null,
    max_withdrawal: '$1,750', profit_target: '$4,000',
    drawdown_limit: 'EOD $1,750', dll: 'None', buffer: false, buffer_amount: null,
    days_to_pass: '1', days_to_payout: '5', eval: null, pa: null, reset_fee: '$139',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Alpha Futures',
  },
  {
    name: 'Phidias 25k Static',
    discount_code: 'RTF',
    overall_score: 4.0,
    platforms: 'Volumetrica, Deepcharts, Deepdom, Quantower, Sierra, ATAS, R|Trader Pro, MotiveWave, Bookmap, Rithmic, NinjaTrader, Tradovate, TradingView',
    account_category: 'Eval',
    fifty_k_all_in: 222, fifty_k_initial_cost: 139, without_discount_usd: 277, discount_usd: 139, discount_percent: 50,
    activation_fee: 83, max_accounts: '5', profit_split: '80/20',
    max_withdrawal: 'None', profit_target: '$1,500',
    drawdown_limit: 'Static $500', dll: 'None', buffer: true, buffer_amount: '$1,600',
    days_to_pass: '1', days_to_payout: '1', eval: 'None', pa: 'None', reset_fee: '$88',
    dca: true, news: true, bots: true, copy_trade: true, vpn: false, micro_scalping: true,
    featured: false, importance: 'medium', group_name: 'Phidias',
  },
  {
    name: 'Phidias 50k (All OTP)',
    discount_code: 'RTF',
    overall_score: 4.0,
    platforms: 'Volumetrica, Deepcharts, Deepdom, Quantower, Sierra, ATAS, R|Trader Pro, MotiveWave, Bookmap, Rithmic, NinjaTrader, Tradovate, TradingView',
    account_category: 'Eval',
    fifty_k_all_in: 116, fifty_k_initial_cost: 116, without_discount_usd: 580, discount_usd: 464, discount_percent: 80,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: '$2,000', profit_target: '$4,000',
    drawdown_limit: 'EOD $2,500', dll: null, buffer: true, buffer_amount: '$2,500',
    days_to_pass: '3', days_to_payout: null, eval: 'None', pa: null, reset_fee: '$30',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'Phidias',
  },
  {
    name: 'BlueBerry Futures Ascent',
    discount_code: 'FUTURES60',
    overall_score: 2.9,
    platforms: 'Blackarrow',
    account_category: 'Eval',
    fifty_k_all_in: 98, fifty_k_initial_cost: 98, without_discount_usd: 245, discount_usd: 147, discount_percent: 60,
    activation_fee: 0, max_accounts: '10', profit_split: '90/10',
    max_withdrawal: '$2,000', profit_target: '$3,000',
    drawdown_limit: 'EOD $2,000', dll: '$1,100', buffer: true, buffer_amount: '$2,000',
    days_to_pass: '2', days_to_payout: '5 min of $150', eval: 'None', pa: '30%', reset_fee: '$79',
    dca: true, news: true, bots: true, copy_trade: true, vpn: false, micro_scalping: true,
    featured: false, importance: 'low', group_name: 'BlueBerry Futures',
  },
  {
    name: 'Blue Guardian Futures Standard Evaluation',
    discount_code: 'RTF',
    overall_score: 3.8,
    platforms: 'Tradovate, NinjaTrader, Volsys/Volbook, Volumetrica',
    account_category: 'Eval',
    fifty_k_all_in: 88, fifty_k_initial_cost: 88, without_discount_usd: 160, discount_usd: 72, discount_percent: 45,
    activation_fee: 0, max_accounts: '3', profit_split: '100% of your first $15,000 then 90/10',
    max_withdrawal: '$1,350', profit_target: '$3,000',
    drawdown_limit: 'EOD $2,500', dll: '$1,250', buffer: false, buffer_amount: null,
    days_to_pass: '1', days_to_payout: '7 min of $100', eval: '0.4', pa: '0.4', reset_fee: '$144',
    dca: true, news: false, bots: false, copy_trade: false, vpn: false, micro_scalping: false,
    featured: false, importance: 'low', group_name: 'Blue Guardian Futures',
  },
  {
    name: 'Blue Guardian Futures Guardian Evaluation',
    discount_code: 'RTF',
    overall_score: 3.8,
    platforms: 'Tradovate, NinjaTrader, Volsys/Volbook, Volumetrica',
    account_category: 'Eval',
    fifty_k_all_in: 65, fifty_k_initial_cost: 65, without_discount_usd: 119, discount_usd: 54, discount_percent: 45,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: '$1,350', profit_target: '$4,000',
    drawdown_limit: 'EOD $2,000', dll: 'None', buffer: true, buffer_amount: '$100',
    days_to_pass: '1', days_to_payout: '14 min of $100', eval: 'None', pa: '0.3', reset_fee: '$107',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'low', group_name: 'Blue Guardian Futures',
  },
  {
    name: 'Elite Trader Funding 1 Step',
    discount_code: 'APRIL80',
    overall_score: 3.8,
    platforms: 'Tradovate, NinjaTrader, TradingView, Investor/RT, MotiveWave, Quantower',
    account_category: 'Eval',
    fifty_k_all_in: 186, fifty_k_initial_cost: 39, without_discount_usd: 197, discount_usd: 158, discount_percent: 80,
    activation_fee: 147, max_accounts: '5', profit_split: '100%',
    max_withdrawal: '$3000', profit_target: '$3,000',
    drawdown_limit: 'Trailing', dll: 'None', buffer: true, buffer_amount: '$100',
    days_to_pass: '5', days_to_payout: 'Same Day Payout Approval', eval: 'None', pa: '40%', reset_fee: '$87',
    dca: true, news: true, bots: false, copy_trade: true, vpn: true, micro_scalping: false,
    featured: false, importance: 'low', group_name: 'Elite Trader Funding',
  },
  {
    name: 'Elite Trader Funding End of Day',
    discount_code: 'APRIL80',
    overall_score: 3.8,
    platforms: 'Tradovate, NinjaTrader, TradingView, Investor/RT, MotiveWave, Quantower',
    account_category: 'Eval',
    fifty_k_all_in: 116, fifty_k_initial_cost: 69, without_discount_usd: 347, discount_usd: 278, discount_percent: 80,
    activation_fee: 47, max_accounts: null, profit_split: null,
    max_withdrawal: '$3,000', profit_target: '$3,000',
    drawdown_limit: 'EOD', dll: '$2,100', buffer: false, buffer_amount: null,
    days_to_pass: '5', days_to_payout: 'Same Day Payout Approval', eval: 'None', pa: '40%', reset_fee: '$87',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'low', group_name: 'Elite Trader Funding',
  },
  {
    name: 'AquaFutures - Beginner',
    discount_code: 'EASTER',
    overall_score: 3.3,
    platforms: 'Quantower, ProjectX, Tradovate, NinjaTrader',
    account_category: 'Eval',
    fifty_k_all_in: 40, fifty_k_initial_cost: 40, without_discount_usd: 100, discount_usd: 60, discount_percent: 60,
    activation_fee: 0, max_accounts: '10', profit_split: '100% of first $15k, then 90/10 thereafter',
    max_withdrawal: '$1,500', profit_target: '$3,000',
    drawdown_limit: 'EOD $2,500', dll: '$1,250', buffer: true, buffer_amount: '$2,500',
    days_to_pass: '1', days_to_payout: 'Weekly', eval: '40% Rule: No single day > 40% of target', pa: null, reset_fee: '$80',
    dca: true, news: true, bots: true, copy_trade: true, vpn: false, micro_scalping: true,
    featured: false, importance: 'low', group_name: 'AquaFutures',
  },
  {
    name: 'AquaFutures - Standard',
    discount_code: 'EASTER',
    overall_score: 3.3,
    platforms: 'Quantower, ProjectX, Tradovate, NinjaTrader',
    account_category: 'Eval',
    fifty_k_all_in: 84, fifty_k_initial_cost: 84, without_discount_usd: 210, discount_usd: 126, discount_percent: 60,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: '$2,000', profit_target: '$4,000',
    drawdown_limit: 'EOD $2,500', dll: 'None', buffer: true, buffer_amount: '$2,500',
    days_to_pass: '1', days_to_payout: 'Bi-Weekly', eval: null, pa: null, reset_fee: '$90',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'low', group_name: 'AquaFutures',
  },
  {
    name: 'FuturesElite - Prime',
    discount_code: 'Use Link For Best Discount',
    overall_score: 4.7,
    platforms: 'Quantower, ProjectX, Volumetrica, ATAS, Deepcharts',
    account_category: 'Eval',
    fifty_k_all_in: 88, fifty_k_initial_cost: 39, without_discount_usd: 49, discount_usd: 10, discount_percent: 20,
    activation_fee: 49, max_accounts: '5', profit_split: '100% (1st $10k), 90% after',
    max_withdrawal: '$1750 for the first 3 payouts', profit_target: '$3,000',
    drawdown_limit: 'Trailing $2000', dll: 'None', buffer: true, buffer_amount: '$2,100',
    days_to_pass: '1', days_to_payout: '7', eval: 'None', pa: '40%', reset_fee: '$87',
    dca: true, news: false, bots: true, copy_trade: true, vpn: false, micro_scalping: false,
    featured: true, importance: 'high', group_name: 'FuturesElite',
  },
  {
    name: 'FuturesElite - Elite',
    discount_code: 'Use Link For Best Discount',
    overall_score: 4.7,
    platforms: 'Quantower, ProjectX, Volumetrica, ATAS, Deepcharts',
    account_category: 'Eval',
    fifty_k_all_in: 103, fifty_k_initial_cost: 103, without_discount_usd: 129, discount_usd: 26, discount_percent: 20,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: null, profit_target: '$3,000',
    drawdown_limit: 'EOD $2000', dll: '$1,250', buffer: true, buffer_amount: '$2,100',
    days_to_pass: '1', days_to_payout: '7', eval: null, pa: null, reset_fee: '$87',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'FuturesElite',
  },
  {
    name: 'GOAT Funded Futures - EOD',
    discount_code: 'Use Link For Best Discount',
    overall_score: null,
    platforms: 'Quantower, ProjectX, Volumetrica, ATAS, Deepcharts, Tradovate, NinjaTrader',
    account_category: 'Eval',
    fifty_k_all_in: 59, fifty_k_initial_cost: 59, without_discount_usd: 124, discount_usd: 65, discount_percent: 52,
    activation_fee: 0, max_accounts: '5', profit_split: '100% of First $10k then 90/10 after',
    max_withdrawal: '$1,500', profit_target: '$3,000',
    drawdown_limit: 'EOD $2000', dll: 'None', buffer: true, buffer_amount: '$100',
    days_to_pass: '3', days_to_payout: '7', eval: '50%', pa: '30%', reset_fee: '$49',
    dca: false, news: false, bots: false, copy_trade: false, vpn: false, micro_scalping: true,
    featured: false, importance: 'medium', group_name: 'GOAT Funded Futures',
  },
  {
    name: 'GOAT Funded Futures - SPRINT',
    discount_code: 'Use Link For Best Discount',
    overall_score: null,
    platforms: 'Quantower, ProjectX, Volumetrica, ATAS, Deepcharts, Tradovate, NinjaTrader',
    account_category: 'Eval',
    fifty_k_all_in: 69, fifty_k_initial_cost: 69, without_discount_usd: 139, discount_usd: 70, discount_percent: 50,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: null, profit_target: null,
    drawdown_limit: 'Intraday trailing Real-time', dll: null, buffer: false, buffer_amount: null,
    days_to_pass: '3', days_to_payout: '5', eval: null, pa: null, reset_fee: '$59',
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'GOAT Funded Futures',
  },
  {
    name: 'FundedSeat - 1 Step (Daily)',
    discount_code: 'RTF',
    overall_score: 4.2,
    platforms: 'Volumetrica, Deepdom, Deepcharts, Quantower, ATAS, Rithmic, TradeSea',
    account_category: 'Eval',
    fifty_k_all_in: 108, fifty_k_initial_cost: 108, without_discount_usd: 270, discount_usd: 162, discount_percent: 60,
    activation_fee: 0, max_accounts: '5', profit_split: '90/10',
    max_withdrawal: '$1,750', profit_target: '$3,000',
    drawdown_limit: 'EOD $2000', dll: 'None', buffer: true, buffer_amount: '$2,100',
    days_to_pass: '1', days_to_payout: '1', eval: '50%', pa: 'N/A', reset_fee: '$120',
    dca: true, news: true, bots: true, copy_trade: true, vpn: false, micro_scalping: false,
    featured: false, importance: 'medium', group_name: 'FundedSeat',
  },
  {
    name: 'FundedSeat - 1 Step (Sprint)',
    discount_code: 'RTF',
    overall_score: 4.2,
    platforms: 'Volumetrica, Deepdom, Deepcharts, Quantower, ATAS, Rithmic, TradeSea',
    account_category: 'Eval',
    fifty_k_all_in: 96, fifty_k_initial_cost: 96, without_discount_usd: 240, discount_usd: 144, discount_percent: 60,
    activation_fee: 0, max_accounts: null, profit_split: null,
    max_withdrawal: null, profit_target: null,
    drawdown_limit: null, dll: '$1,200', buffer: false, buffer_amount: null,
    days_to_pass: null, days_to_payout: 'Daily After 1st Payout', eval: 'N/A', pa: '20%', reset_fee: null,
    dca: null, news: null, bots: null, copy_trade: null, vpn: null, micro_scalping: null,
    featured: false, importance: 'medium', group_name: 'FundedSeat',
  },
];

const importFirms = async () => {
  const client = await pool.connect();
  let inserted = 0;
  let skipped = 0;

  try {
    for (const firm of firms) {
      const exists = await client.query('SELECT id FROM prop_firms WHERE name = $1', [firm.name]);
      if (exists.rows.length > 0) {
        console.log(`⏭️  Skipped (exists): ${firm.name}`);
        skipped++;
        continue;
      }

      const score = firm.overall_score;
      const color = statusColor(score);

      await client.query(`
        INSERT INTO prop_firms (
          name, importance, featured, rating, overall_score, platforms, account_category,
          fifty_k_all_in, fifty_k_initial_cost, without_discount_usd, discount_usd, discount_percent,
          activation_fee, max_accounts, profit_split, max_withdrawal, profit_target,
          drawdown_limit, dll, buffer, buffer_amount, days_to_pass, days_to_payout,
          eval, pa, reset_fee, dca, news, bots, copy_trade, vpn, micro_scalping,
          discount_code, status_color, group_name
        ) VALUES (
          $1,$2,$3,$4,$5,$6,$7,
          $8,$9,$10,$11,$12,
          $13,$14,$15,$16,$17,
          $18,$19,$20,$21,$22,$23,
          $24,$25,$26,$27,$28,$29,$30,$31,$32,
          $33,$34,$35
        )
      `, [
        firm.name, firm.importance || 'medium', firm.featured || false, score, score, firm.platforms, firm.account_category,
        firm.fifty_k_all_in, firm.fifty_k_initial_cost, firm.without_discount_usd, firm.discount_usd, firm.discount_percent,
        firm.activation_fee || 0, firm.max_accounts, firm.profit_split, firm.max_withdrawal, firm.profit_target,
        firm.drawdown_limit, firm.dll, firm.buffer || false, firm.buffer_amount, firm.days_to_pass, firm.days_to_payout,
        firm.eval, firm.pa, firm.reset_fee, firm.dca, firm.news, firm.bots, firm.copy_trade, firm.vpn, firm.micro_scalping,
        firm.discount_code, color, firm.group_name,
      ]);

      console.log(`✅  Inserted: ${firm.name}`);
      inserted++;
    }

    console.log(`\n🎉  Done! ${inserted} inserted, ${skipped} skipped.`);
  } catch (err) {
    console.error('❌  Error:', err.message, err.detail || '');
  } finally {
    client.release();
    process.exit(0);
  }
};

importFirms();
