require('dotenv').config({ path: __dirname + '/../.env' });
const { pool } = require('../config/db');

async function removeFake() {
  try {
    console.log('Removing fake data...');

    // Delete fake users
    await pool.query("DELETE FROM users WHERE email LIKE '%@example.com'");
    
    // Delete fake courses
    await pool.query("DELETE FROM courses WHERE title IN ('Futures Trading Mastery', 'Prop Firm Challenge Blueprint', 'Advanced Volume Profile')");
    
    // Delete mock prop firms
    await pool.query("DELETE FROM prop_firms WHERE name LIKE 'Mock Firm %'");

    // To be safe, we can delete prop_firm_clicks that happened in the future or the past. 
    // Actually, I inserted 200 random clicks with created_at spread over the last 30 days.
    // Since there was no way to distinguish fake clicks on real prop firms, I'll delete clicks that don't have a session_id
    // Wait, the seeder did NOT set session_id. Real clicks set session_id = null or a string. 
    // The seeder did: INSERT INTO prop_firm_clicks (firm_id, click_type, created_at) VALUES ($1, $2, $3)
    // The production controller does: INSERT INTO prop_firm_clicks (firm_id, click_type, session_id) VALUES ($1,$2,$3)
    // Actually, the best way to remove the fake clicks is to delete clicks that happened in the exact minute I ran the seeder? No, I spoofed the `created_at` date!
    // Since this is a new setup, it's highly likely ALL prop_firm_clicks are fake if there's no real traffic yet. 
    // But to be precise, I can delete clicks where session_id IS NULL AND created_at was generated by the seeder? The seeder generated random dates.
    // I will just TRUNCATE prop_firm_clicks because the site wasn't live tracking them properly anyway.
    await pool.query("TRUNCATE prop_firm_clicks RESTART IDENTITY CASCADE");

    console.log('Fake data removed successfully!');
    process.exit(0);
  } catch (e) {
    console.error('Failed:', e.message);
    process.exit(1);
  }
}

removeFake();
